### ISSUE TITLE
missing template

### ISSUE THREAD

**Issue by xrotwang** [clld/valpal#2]
```
Traceback (most recent call last):
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid_exclog/__init__.py", line 134, in exclog_tween
    response = handler(request)
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 178, in tm_tween
    reraise(*exc_info)
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 143, in tm_tween
    response = handler(request)
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid/util.py", line 733, in reraise
    raise value
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid/router.py", line 144, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid/viewderivers.py", line 451, in rendered_view
    request, result, view_inst, context
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid/renderers.py", line 443, in render_view
    return self.render_to_response(response, system, request=request)
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid/renderers.py", line 466, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid/renderers.py", line 462, in render
    result = renderer(value, system_values)
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid_mako/__init__.py", line 144, in __call__
    template = self.template
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid_mako/__init__.py", line 117, in template
    template = self.lookup.get_template(spec)
  File "/usr/venvs/valpal/lib/python3.6/site-packages/pyramid_mako/__init__.py", line 75, in get_template
    "Can not locate template for uri %r" % uri)
mako.exceptions.TopLevelLookupException: Can not locate template for uri 'valpal:credits.mako'
```

**Comment by johenglisch** [comment]
Oh, okay -- I just [forgot to push](https://github.com/clld/valpal/commit/8f293d88d7a85744df610a26c4d1a2ce5fe31a03)
